### ISSUE TITLE
dockerfile does not complete, saying "Docker Deployed"

### ISSUE THREAD

**Issue by hubingkang** [Dokploy/dokploy#155] opened 2024-06-21 09:05 UTC
### To Reproduce

dockerfile does not complete, saying "Docker Deployed"

### Current vs. Expected behavior

<img width="898" alt="image" src="https://github.com/Dokploy/dokploy/assets/43019786/89afe886-5298-48e7-b92d-3f13d5bf6f4e">

Complete all dockerfile steps

### Provide environment information

```bash
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
EXPOSE 8000
CMD [ "pnpm", "start" ]
```

### Which area(s) are affected? (Select all that apply)

Docker

### Additional context

Docker version 26.0.0, build 2ae903e

**Comment by Siumauricio** [comment] 2024-06-22 03:47
The dockerfile looks good, does the application run once the build is finished?

**Comment by hubingkang** [comment] 2024-06-25 11:24
There is an error during docker deployment, but this log does not see the error message

**Comment by Siumauricio** [comment] 2024-06-26 06:33
We use the native docker builder, so surely there is some error or suddenly we are not showing some important log that shows the error but for that I would need the following:


1. minimum repository with the minimum things to be able to test and reproduce the problem.

**Comment by thenglong** [comment] 2024-06-26 16:45
@hubingkang Did you find a solution for this? I face the same issue at `RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
`

**Comment by Siumauricio** [comment] 2024-06-27 02:34
@hubingkang Can you share the dockerfile and the project you are building?

**Comment by hubingkang** [comment] 2024-06-27 04:40
@thenglong @Siumauricio  I didn't use the dockerfile from pnpm
```
FROM node:20-slim AS base

RUN npm install -g pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install
COPY . .
RUN pnpm run build
```

**Comment by thenglong** [comment] 2024-06-27 04:46
This is weird because I ran build dockerfile from pnpm instruction manually works but via Dokploy didn't. This is the line in Dockerfile that causes the problem in Dokploy

`RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile`

**Comment by thenglong** [comment] 2024-06-27 04:47
@hubingkang Shall we reopen this?

**Comment by hubingkang** [comment] 2024-06-27 04:52
> This is weird because I ran build dockerfile from pnpm instruction manually works but via Dokploy didn't. This is the line in Dockerfile that causes the problem in Dokploy
> 
> `RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile`

Similarly, I successfully deployed it using docker directly on my computer

**Comment by Siumauricio** [comment] 2024-06-27 06:46
It seems that the problem does not come from dokploy but from something external, checking very carefully in the logs locally it seems that it is something related to BuildKit that needs to be activated and comes from the dockerode library which we use to build the images when you use the Docker provider, according to investigating there seems to be an open issue about this,

![Screenshot 2024-06-27 at 12 33 51 AM](https://github.com/Dokploy/dokploy/assets/47042324/ac9d98a4-a25c-4b3e-9749-e121fe53523e)


https://github.com/apocas/dockerode/issues/601
https://github.com/testcontainers/testcontainers-node/issues/571

A solution will be to remove the --mount=type=cache

and use like this https://github.com/Dokploy/swarm-test/tree/dockerfile

```dockerfile
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS prod-deps
RUN pnpm install --prod --frozen-lockfile

FROM base AS build
RUN pnpm install --frozen-lockfile
RUN pnpm run build

FROM base
COPY --from=prod-deps /app/node_modules /app/node_modules
EXPOSE 3000
CMD [ "pnpm", "start" ]

```

**Comment by Siumauricio** [comment] 2024-07-01 04:39
Since this is more of a dockerode issue, we can close it for now, when the issue is resolved we will update and the problem should go away, anyways there is a workaround for now

**Closed by Siumauricio** 2024-07-01 04:39 UTC
Labels: bug, workaround
