### ISSUE TITLE
Pathprefix for domain is not added to traefik when using a compose project.

### ISSUE THREAD

**Issue by visualies** [Dokploy/dokploy#676] opened 2024-11-10 23:43 UTC
### To Reproduce

1. Create a basic compose project eg. nginx.
2. Add a custom domain with a path eg. /api
3. Check the generated docker-compose.yml with preview compose.

### Current vs. Expected behavior

It should add the pathprefix to the traefik labels the same way it works when using projects from git etc.
Currently its not possible to differentiate based on path with compose based projects.

### Provide environment information

```bash
OS: Debian 12
VPS: Hetzner
Dokploy Version: v0.10.4
```

### Which area(s) are affected? (Select all that apply)

Application, Docker Compose, Traefik, Docker

**Comment by Siumauricio** [comment] 2024-11-10 23:46
Duplicate of #648

**Closed** 2024-11-10 23:46 UTC
Labels: bug
