### ISSUE TITLE
Cannot connect to database using internal url

### ISSUE THREAD

**Issue by joshfester** [Dokploy/dokploy#561] opened 2024-10-16 17:22 UTC
### To Reproduce

1. Create a postgres database
2. Create a Ruby on Rails app in the same project
3. Set the DATABASE_URL env variable to the internal postgres url

### Current vs. Expected behavior

When trying to deploy a Rails app using nixpacks, I get this error:

PG::ConnectionBad: could not translate host name "northcentralai-postgres-031ff5" to address: Name or service not known (PG::ConnectionBad)

Is there some extra step to make the postgres host name available to the rails app?

### Provide environment information

```bash
OS: Ubuntu 24.04
Host: Hetzner
Dokploy: 0.10.0
Postgres Image: postgres:16
Ruby: 3.3.5
```

### Which area(s) are affected? (Select all that apply)

Application, Databases

**Comment by joshfester** [comment] 2024-10-16 17:37
When I switched the builder from Nixpacks to Heroku Buildpacks, the app deployed and worked. I would like to use Nixpacks instead if possible though

**Comment by joshfester** [comment] 2024-10-16 17:40
I tried switching the builder to use a Dockerfile and I tried Heroku Buildpacks. Both ran into the same issue connecting to the database

**Comment by Siumauricio** [comment] 2024-10-16 19:10
Duplicate of #507

**Closed** 2024-10-18 07:09 UTC
Labels: bug
